// Centralize result-screen copy so visual tweaks do not require editing JSX.
export const RESULT_SCREEN_COPY = {
  sessionSummary: 'Session Summary',
  sessionDescription: '查看本章表现、回顾错词，并决定接下来是进入下一章还是再练一次。',
  mistakeReview: 'Mistake Review',
  perfectRun: 'Perfect Run',
  zeroMistakeTitle: '本章零失误',
  mistakeReviewTitle: '错词回看',
  totalMistakesLabel: '共 {count} 个错词',
  zeroMistakeCount: '0 个错词',
  zeroMistakeDescription: '这一章的拼写和节奏都很稳，可以直接进入下一章，或者再来一次把速度也一起拉高。',
  exitTitle: '退出结果页',
  authorTitle: '作者主页',
  shareTitle: '分享结果',
  exportTitle: '导出本章结果',
  donateTitle: '支持这个项目',
  githubTitle: '查看 GitHub 仓库',
  reviewChapterSuffix: '复习',
  chapterLabel: (chapter: number) => `第 ${chapter} 章`,
  reviewOtherChapters: '练习其他章节',
  reviewOtherChaptersTooltip: '返回词库选择其他章节',
  chapterDictation: '本章听写',
  chapterDictationTooltip: '快捷键：Shift + Enter',
  repeatChapter: '重新练习本章',
  repeatChapterTooltip: '快捷键：Space',
  nextChapter: '下一章',
  nextChapterTooltip: '快捷键：Enter',
  metricAccuracy: '正确率',
  metricTime: '用时',
  metricWpm: 'WPM',
  xlsxLoadFailed: '加载 xlsx 模块失败',
} as const;
